### ISSUE TITLE
Ganztagestermine einen Tag zu früh

### ISSUE THREAD

**Issue by morbificagent** [grommunio/grommunio-dav#2]
Hallo zusammen,

Bei der Verwendung von CalDAV sind Ganztagestermine nicht am korrekten Tag angezeigt sondern einen Tag zu früh.
Im Webinterface ist alles ok.

Habe nun drei verschiedene CalDAV Clients getestet und alle stellen die Ganztagestermine einen Tag zu früh dar.
Das gilt auch für mehrtägige Ganztages-Termine.

Habe auch im Grommunio-Forum gepostet, aber da noch keine Antwort bekommen.
Somit sorry fürs "Doppelposten"

**Comment by jengelh** [comment]
gromox-2.32-74-g9b2e2120c
